### ISSUE TITLE
S02 has no tests

### ISSUE THREAD

**Issue by mds3dstn71** [mds3dstn71/bryce#39]
This small project will be a good opportunity to practice writing some tests. Would be nice if CI tools are also incorporated.

**Tasks:**

- [x] Learn about Mocha, etc.
- [x] Pick a framework and/or library [1]
- [x] Apply tests and/or frameworks to project [2]
- [x] Learn about Travis CI
- [x] Apply Travis CI tool to project

**Notes:**

[1] Choose Mocha, Chai, Sinon stack
[2] Running ESLint is still a test 😛
